// Generate JSON Schemas for the agent-facing leaf contracts from the Pump Up SDK types
// (themselves generated from backend/openapi.yaml). Run via `npm run gen:schemas`. The output is
// a committed, regenerated artifact — single source of truth, no hand-maintained copy. Emitted to
// two consumers: this plugin's TS module, and the sibling Hermes plugin's JSON (public/hermes-plugin).
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { createGenerator } from "ts-json-schema-generator";

const SDK_TYPES = "../../sdks/typescript/api/types";
const TS_OUT = "src/generated/contract-schemas.ts";
const JSON_OUT = "../hermes-plugin/pumpup_hermes/generated/contract_schemas.json";

/// One SDK type to emit: the source file, the type name, the TS export const, and the JSON key.
const TARGETS = [
  { type: "Field", file: `${SDK_TYPES}/Field.ts`, export: "fieldSchema", key: "field" },
  { type: "ApprovalRecommendation", file: `${SDK_TYPES}/ApprovalRecommendation.ts`, export: "approvalRecommendationSchema", key: "approvalRecommendation" },
  { type: "FieldBid", file: `${SDK_TYPES}/FieldBid.ts`, export: "fieldBidSchema", key: "fieldBid" },
  { type: "MetadataPatchDto", file: `${SDK_TYPES}/MetadataPatchDto.ts`, export: "metadataPatchSchema", key: "metadataPatch" },
];

const lines = ["// Generated by `npm run gen:schemas` from the Pump Up SDK types — do not edit by hand."];
const contracts = {};
for (const target of TARGETS) {
  const generator = createGenerator({
    path: target.file,
    tsconfig: "tsconfig.codegen.json",
    type: target.type,
    expose: "none",
    topRef: false,
    skipTypeCheck: true,
    additionalProperties: false,
  });
  const schema = generator.createSchema(target.type);
  delete schema.$schema;
  lines.push(`export const ${target.export} = ${JSON.stringify(schema)};`);
  contracts[target.key] = schema;
}

mkdirSync(dirname(TS_OUT), { recursive: true });
writeFileSync(TS_OUT, `${lines.join("\n")}\n`);
mkdirSync(dirname(JSON_OUT), { recursive: true });
writeFileSync(JSON_OUT, `${JSON.stringify(contracts, null, 2)}\n`);
console.log(`gen-schemas: wrote ${TS_OUT} + ${JSON_OUT} (${TARGETS.map((t) => t.type).join(", ")})`);
