// Generate JSON Schemas for the agent-facing leaf contracts from the Pump Up SDK types
// (themselves generated from backend/openapi.yaml). Run via `npm run gen:schemas`. The output is
// a committed, regenerated artifact — single source of truth, no hand-maintained copy.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { createGenerator } from "ts-json-schema-generator";

const SDK_TYPES = "../../sdks/typescript/api/types";
const OUT = "src/generated/contract-schemas.ts";

/// One SDK type to emit: the source file, the type name, and the exported const.
const TARGETS = [
  { type: "Field", file: `${SDK_TYPES}/Field.ts`, export: "fieldSchema" },
  { type: "ApprovalRecommendation", file: `${SDK_TYPES}/ApprovalRecommendation.ts`, export: "approvalRecommendationSchema" },
  { type: "FieldBid", file: `${SDK_TYPES}/FieldBid.ts`, export: "fieldBidSchema" },
  { type: "MetadataPatchDto", file: `${SDK_TYPES}/MetadataPatchDto.ts`, export: "metadataPatchSchema" },
];

const lines = ["// Generated by `npm run gen:schemas` from the Pump Up SDK types — do not edit by hand."];
for (const target of TARGETS) {
  const generator = createGenerator({
    path: target.file,
    tsconfig: "tsconfig.codegen.json",
    type: target.type,
    expose: "none",
    topRef: false,
    skipTypeCheck: true,
    additionalProperties: false,
  });
  const schema = generator.createSchema(target.type);
  delete schema.$schema;
  lines.push(`export const ${target.export} = ${JSON.stringify(schema)};`);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${lines.join("\n")}\n`);
console.log(`gen-schemas: wrote ${OUT} (${TARGETS.map((t) => t.type).join(", ")})`);
