// Embed the single-source agent guide (public/pumpup-agent-guide.md) into the plugin packages.
// Run via `npm run gen:guide`. Outputs are committed, regenerated artifacts — no hand-maintained
// copy. Two consumers per host: the `pumpup_guide` tool (a string const) and the host skill
// (a SKILL.md). Emits the OpenClaw artifacts here and the sibling Hermes artifacts in lockstep.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const SRC = "../pumpup-agent-guide.md";

/// Frontmatter description shared by both host skills — the index line a host ranks for relevance.
const SKILL_DESCRIPTION =
  "How to use the Pump Up human-in-the-loop tools: when to request an approval or elicitation, the " +
  "pending/resume model (end your turn, don't busy-poll), and recording timeline events.";

const guide = readFileSync(SRC, "utf8").trimEnd();

/// SKILL.md = `name`/`description` frontmatter + the guide body.
function skillDoc(name) {
  return `---\nname: ${name}\ndescription: ${SKILL_DESCRIPTION}\n---\n\n${guide}\n`;
}

/// Write `content` to `path`, creating parent dirs.
function emit(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const tsConst =
  "// Generated by `npm run gen:guide` from public/pumpup-agent-guide.md — do not edit by hand.\n" +
  `export const agentGuide = ${JSON.stringify(guide)};\n`;

// OpenClaw: a TS const for the tool + a SKILL.md for the auto-surfaced skill.
emit("src/generated/agent-guide.ts", tsConst);
emit("skills/pumpup/SKILL.md", skillDoc("pumpup"));

// Hermes: a plain-markdown data file for the tool (read at runtime, like contract_schemas.json) + a
// SKILL.md for the `pumpup:guide` skill (register_skill).
const HERMES = "../hermes-plugin/pumpup_hermes";
emit(`${HERMES}/generated/agent_guide.md`, `${guide}\n`);
emit(`${HERMES}/skills/guide/SKILL.md`, skillDoc("guide"));

console.log("gen-guide: wrote OpenClaw (agent-guide.ts, skills/pumpup) + Hermes (agent_guide.md, skills/guide)");
